name: Daily Longball Labs Report

on:
  schedule:
    # Run at 10:00 AM UTC every day (adjust as needed)
    - cron: "0 10 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # No need to download logo since it's stored in the repository

      - name: Generate report
        env:
          # Email Config
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER || 'smtp.gmail.com' }}
          SMTP_PORT: ${{ secrets.SMTP_PORT || '587' }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
          SEND_EMAIL: ${{ secrets.SEND_EMAIL || 'true' }}

          # Data Config
          LABELED_PLAYERS: ${{ secrets.LABELED_PLAYERS }}
          URL_FANGRAPHS: ${{ secrets.URL_FANGRAPHS || 'https://www.fangraphs.com/guts.aspx?type=cn' }}

          # Paths
          DATA_DIR: "./data"
          OUTPUT_DIR: "./output"
          LOGO_PATH: "./longball-labs.png" # Path to the logo in the repository root
        run: |
          mkdir -p data output
          python frj_bot.py

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-lbl-report
          path: ./output/daily_lbl_report.pdf
          retention-days: 7
